// Generated by CoffeeScript 1.5.0
(function() {

  define(['jquery'], function($) {
    var selectors, shuffle;
    selectors = {
      navigation: ['#nav-home', '#nav-work', '#nav-about', '#nav-contact'],
      pageContainer: '#page-container',
      page: '.page',
      item: '.page .item',
      overlay: '.page .item .overlay'
    };
    shuffle = function(array) {
      var a, b, j, len;
      len = array.length;
      if (len === 0) {
        return array;
      }
      while (--len) {
        j = Math.floor(Math.random() * (len + 1));
        a = array[len];
        b = array[j];
        array[len] = b;
        array[j] = a;
      }
      return array;
    };
    return $(function() {
      var i, selector, _i, _len, _ref, _results;
      (function() {
        var i, interval, items;
        i = 0;
        items = shuffle($(selectors.item));
        return interval = setInterval(function() {
          if (i >= items.length) {
            clearInterval(interval);
          }
          $(items[i]).animate({
            opacity: 1
          });
          return i += 1;
        }, 150);
      })();
      $(selectors.item).mouseenter(function(e) {
        return $(this).children('.overlay').show().animate({
          opacity: 0.8
        }, 'fast');
      }).mouseleave(function(e) {
        return $(this).children('.overlay').animate({
          opacity: 0
        }, 'fast');
      });
      _ref = selectors.navigation;
      _results = [];
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        selector = _ref[i];
        _results.push((function(selector, i) {
          return $(selector).click(function(e) {
            var height;
            e.preventDefault();
            height = $("" + selectors.pageContainer + "             " + selectors.page + ":nth-child(" + (i + 1) + ")").height();
            $('.content').animate({
              height: height
            });
            return $(selectors.pageContainer).animate({
              "margin-left": "" + (-960 * i) + "px"
            });
          });
        })(selector, i));
      }
      return _results;
    });
  });

}).call(this);
